language: bash

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - bash-completion

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --rc
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bash-completion@2 gnu-getopt; fi

script:
  - ./tests/test
